// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyIdealized(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<string>;

export function ApplySummary(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<void>;

export function BranchFrom(arg1:string,arg2:string,arg3:string):Promise<void>;

export function BranchNewSession(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CheckUpdate():Promise<main.UpdateInfo>;

export function DoUpdate(arg1:string):Promise<void>;

export function EditMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ExecClaude(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<void>;

export function GetAvailableTerminals():Promise<Array<string>>;

export function GetClaudeCommand(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function GetConversation(arg1:string,arg2:string):Promise<main.Conversation>;

export function GetStartupArgs():Promise<main.StartupArgs>;

export function GetVersion():Promise<string>;

export function IdealizeMessages(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function InsertMessage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ListProjects():Promise<Array<main.Project>>;

export function ListSessions(arg1:string):Promise<Array<main.Session>>;

export function RestoreSidechain(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveConversation(arg1:string,arg2:string,arg3:main.SaveRequest):Promise<main.SaveResult>;

export function SummarizeMessages(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;
