// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConversation(arg1:string,arg2:string):Promise<main.Conversation>;

export function ListProjects():Promise<Array<main.Project>>;

export function ListSessions(arg1:string):Promise<Array<main.Session>>;

export function SaveConversation(arg1:string,arg2:string,arg3:main.SaveRequest):Promise<main.SaveResult>;
