// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyIdealized(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ApplyIdealized'](arg1, arg2, arg3, arg4);
}

export function ApplySummary(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ApplySummary'](arg1, arg2, arg3, arg4);
}

export function BranchFrom(arg1, arg2, arg3) {
  return window['go']['main']['App']['BranchFrom'](arg1, arg2, arg3);
}

export function BranchNewSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['BranchNewSession'](arg1, arg2, arg3);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function DoUpdate(arg1) {
  return window['go']['main']['App']['DoUpdate'](arg1);
}

export function EditMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditMessage'](arg1, arg2, arg3, arg4);
}

export function ExecClaude(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecClaude'](arg1, arg2, arg3, arg4);
}

export function GetAvailableTerminals() {
  return window['go']['main']['App']['GetAvailableTerminals']();
}

export function GetClaudeCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetClaudeCommand'](arg1, arg2, arg3);
}

export function GetConversation(arg1, arg2) {
  return window['go']['main']['App']['GetConversation'](arg1, arg2);
}

export function GetStartupArgs() {
  return window['go']['main']['App']['GetStartupArgs']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IdealizeMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['IdealizeMessages'](arg1, arg2, arg3);
}

export function InsertMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['InsertMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListSessions(arg1) {
  return window['go']['main']['App']['ListSessions'](arg1);
}

export function RestoreSidechain(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreSidechain'](arg1, arg2, arg3);
}

export function SaveConversation(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveConversation'](arg1, arg2, arg3);
}

export function SummarizeMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['SummarizeMessages'](arg1, arg2, arg3);
}
