// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConversation(arg1, arg2) {
  return window['go']['main']['App']['GetConversation'](arg1, arg2);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListSessions(arg1) {
  return window['go']['main']['App']['ListSessions'](arg1);
}

export function SaveConversation(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveConversation'](arg1, arg2, arg3);
}
